function [q22mask,is22q] = PROCESS_SCANIDS(demoMatch,subjInd_scanID)

% INPUTS:
% demoMatch: demographics table generated by code/process/ProcessData22q.m
% subjInd_scanID: cell array for each scan (here only 1 scan) with nsubjects x 1 vector relating 
% scanid to index in concTS BOLD data. generated by code/process/ProcessData22q.m
%
% OUTPUTS:
% q22mask: logical mask that can be applied to BOLD data to select 22q BOLD data
% is22q: binary indicator that can be applied to demographics to select 22q demographics/subjects

	
q22mask = ismember(subjInd_scanID{1},cellstr(num2str(demoMatch.scanid(strcmp(demoMatch.study,'22q')))));
is22q = double(strcmp(demoMatch.study, '22q'));