function [concTS_null,design_matrix_null] = NULL_IMPLEMENT(null_spec,concTS,subjInd,design_matrix,name_root)

% INPUTS:
% null_spec: character vector specifying which null model to implement
% concTS: concatenated BOLD time series matrix that is (subjects*# TRs per scan)x(regions or parcels)
% subjInd: indicator vector that is (subjects*# TRs per scan)x1, labeled 1:N indicating which TRs belong
% to which subject
% design_matrix: FIR design matrix struct, generated by code/fir/fir_design.m
% name_root: name of pipeline run
%
% OUTPUTS:
% concTS_null: concTS, with null model implemented
% design_matrix_null: design_matrix, with null model implemented

if strcmp(null_spec,'IPR')
	% this null model phase randomizes each channel independently while preserving power spectrum
	% phase randomization performed within each subject

    %f=figure; subplot(1,2,1); imagesc(concTS(1:204,:));
    rng(0); % just doing one rep so set seed to the same value here and in fir_pca_bootstrap_prep
    concTS_null = IPR_BOLD_NULL(concTS,subjInd);
    %subplot(1,2,2); imagesc(concTS(1:204,:));
elseif strcmp(null_spec,'UPR')
	% this null model introduces the same random phase offset to all channels, within each subject
	% (not used in this paper)

    %f=figure; subplot(1,2,1); imagesc(concTS(1:204,:));
    rng(0);
    concTS_null = UPR_BOLD_NULL(concTS,subjInd);
    %subplot(1,2,2); imagesc(concTS(1:204,:));
elseif strcmp(null_spec,'GoodPerformers75')
	% this null model removes any subjects with poor performance, per 'code/cognition/fir_pca_cognition_lm.R'
	idemo_performance = readtable(fullfile('results',name_root,'analyses/behavior/idemo/IDEmoAccuracy.csv'),'TreatAsEmpty','NA')
	load(['data/Demographics',name_root,'.mat'],'demoMatch');
	% tested that scanids are in right order of subjInd:
	% ss = cell2mat(cellfun(@(x) str2num(x),subjInd_scanID{1},'UniformOutput',false));
	% all(ss==idemo_performance.scanid)
	% all(ss==demoMatch.scanid)

	excl_pairs = demoMatch.match_pair(idemo_performance.allcorrect < 0.75); % get match pairs to exclude
	excl_ind = find(ismember(demoMatch.match_pair,excl_pairs)); % get subjInd for subjects to exclude
	idemo_performance.allcorrect(excl_ind) = NaN; % NaN out MATCH PAIRS
	excl_ind_all = find(isnan(idemo_performance.allcorrect)); % also remove the match pairs who don't have performance data (think they are already NaN anyways)
	design_matrix.X(:,ismember(design_matrix.columnLabelsSubject,excl_ind_all)) = NaN; % remove subjects as above from design matrix
	design_matrix_null = design_matrix;
	concTS_null = concTS; 
else
	% if no null model specified, don't change the matrices at all
	concTS_null = concTS;
	design_matrix_null = design_matrix;

end